[server]
enableCORS = false
enableXsrfProtection = false
port = 8501

[client]
showErrorDetails = false

[logger]
level = "info"

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
